### ISSUE TITLE
Server CPU 100% sustained when used with SkyFactory

### ISSUE THREAD

**Issue by Benjawa1** [vorquel/SimpleSkyGrid#11]
I am running a SkyFactory 2.4 server (Private). I am attempting to use your mod to create a SkyGrid world. 

The server CPU usage spikes to 100% (without anyone connecting) and stays there. At first, connections go normally but block lag is horrible. It can take up to a full minute before the broken block breaks, although displays on screen correctly and immediately re-appears. 

After about 20 minutes of run time regular lag starts and begins timing out players.

Attempting to stop the server can take up to 30 minutes without killing the process. 

I remove SkyGrid and restart with a fresh world, none of this occurs. 

If you can tell me what logs you would like, I will get them uploaded to you as soon as possible. 

A user account for you can be arranged if you need to get onto the server.

**Comment by Benjawa1** [comment]
UPDATE:

Added the mod back and generated a new world.

Shutdown (had to kill the process) and then removed SkyGrid

Now that the world is generated, it seems to be working fine.

There was a lot of start up lag due to all the liquids flowing, and a redwood tree that grew.

Now things seem to be running ok.

**Comment by Benjawa1** [comment]
Nevermind, now that all the liquids and trees have grown, it has become unplayable.

**Comment by Vorquel** [comment]
The latest version of Simple Sky Grid attempts to combat lag by preventing saplings and liquids from ticking until hit by a player. Either you aren't using the most recent version of Simple Sky Grid, or else this feature is broken on servers. What version of Simple Sky Grid are you using?

**Comment by Benjawa1** [comment]
2.5.3 I believe, I downloaded it this morning from curse.

Sent via the Samsung Galaxy S7, an AT&T 4G LTE smartphone
-------- Original message --------From: Vorquel notifications@github.com Date: 4/5/16  6:15 PM  (GMT-06:00) To: Vorquel/SimpleSkyGrid SimpleSkyGrid@noreply.github.com Cc: Benjawa1 benjawa1@gmail.com Subject: Re: [Vorquel/SimpleSkyGrid] Server CPU 100% sustained when used with
  SkyFactory (#11) 
The latest version of Simple Sky Grid attempts to combat lag by preventing saplings and liquids from ticking until hit by a player. Either you aren't using the most recent version of Simple Sky Grid, or else this feature is broken on servers. What version of Simple Sky Grid are you using?

**Comment by Benjawa1** [comment]
Yes, SimpleSkyGrid-1.7.10-2.5.3.jar is the file I am using. 

What else can I get you?

**Comment by Benjawa1** [comment]
Any luck?

**Comment by Vorquel** [comment]
I can reproduce the issue, but I haven't pinned down why exactly it's happening.

**Comment by Benjawa1** [comment]
Ok, thank you for the update. I will be happy to help out in any way that I can.

**Comment by Vorquel** [comment]
Bad news, what I thought was the bug is just a visual glitch. I think I figured out the root cause of your problem, and I really should have figured it out sooner. I don't think your server is good enough to handle a skygrid style map.

**Comment by Benjawa1** [comment]
More memory or processors?

**Comment by Vorquel** [comment]
From what you've told me, better processors. I'm not a server admin though. Professionals would be better equipped to answer your questions.

**Comment by Benjawa1** [comment]
I am, so I will assign some more and see what I can do. Thank you very much for your help.

**Comment by Vorquel** [comment]
Your welcome, and good luck.

**Comment by Benjawa1** [comment]
I wanted to let you know I found the fix to the issue. I turns out it was not my processor. It was the version of Forge I was using, plus the addition of Forge Essentials and FastCraft.

Current Forge version I am using: forge-1.7.10-10.13.4.1614-1.7.10-universal
Current Forge Essentials Version : forgeessentials-1.7.10-1.4.4.1164-server
Current FastCraft Version: fastcraft-1.23

Just updating Forge to 10.13.4.1614 showed the most improvement, along with some additional Java perimeters. Having Java use multiple processors helped too. Those are below. 

 -Xmx4G -Xms2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalPacing -XX:ParallelGCThreads=4 -XX:+AggressiveOpts -XX:NewRatio=3 -XX:SurvivorRatio=3 -XX:TargetSurvivorRatio=80 -XX:MaxTenuringThreshold=8 -XX:+UseParNewGC -XX:MaxGCPauseMillis=10 -XX:GCPauseIntervalMillis=50 -XX:MaxGCMinorPauseMillis=7 -XX:+ExplicitGCInvokesConcurrent -XX:+UseCMSInitiatingOccupancyOnly -XX:CMSInitiatingOccupancyFraction=60 -XX:+BindGCTaskThreadsToCPUs -Xnoclassgc -Dfml.queryResult=confirm -jar forge-1.7.10-10.13.4.1614-1.7.10-universal.jar nogui

At the end of the day, though, just updating Forge did not get the processor off 100% (Sometimes as high as 350%) It was playable, but just barely and for most folks it would just be too annoying. After some more research I found that Forge Essentials has some server Optimization stuff in it and added that. It increased performance by about 10%, but still not good enough. When I added FastCraft to the server, the processor usage has never spiked above 50%. 

I am tempted to remove FE and try it with the new Forge and FastCraft, but if it ain't broke....

Besides, for server administration FE seems to be very nice, but I will have to take some time to learn it. 

I am currently doing a full play through to see if the latest version of Forge will affect the rest of the mods in the SkyFactory 2.4 modpack. And, I hope to get your mod included in the 2.5 version Bacon is currently working on as well. 

Let me know if you need any other information on how this turned out and I will be happy to provide what I can. Thank you for your support.
